name: Check
on:
  workflow_call:
    inputs:
      baseBranch:
        required: true
        type: string
      headBranch:
        required: true
        type: string
permissions: {}
defaults:
  run:
    shell: bash
jobs:
  no-channel-base:
    name: no channel base
    if: contains(fromJSON(inputs.baseBranch).type, 'channel')
    runs-on: ubuntu-latest
    steps:
    - run: 'cat <<EOF

        The nixos-* and nixpkgs-* branches are pushed to by the channel

        release script and should not be merged into directly.


        Please target the equivalent release-* branch or master instead.

        EOF

        exit 1

        '
  cherry-pick:
    if: 'github.event_name == ''pull_request'' ||

      (fromJSON(inputs.baseBranch).stable && !contains(fromJSON(inputs.headBranch).type,
      ''development''))

      '
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        fetch-depth: 0
        filter: tree:0
        path: trusted
    - name: Check cherry-picks
      id: check
      continue-on-error: true
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: './trusted/ci/check-cherry-picks.sh "$BASE_SHA" "$HEAD_SHA" checked-cherry-picks.md

        '
    - name: Log current API rate limits
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh api /rate_limit | jq
    - name: Prepare review
      if: steps.check.outcome == 'failure'
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: "const { readFile, writeFile } = require('node:fs/promises')\n\nconst\
          \ job_url = (await github.rest.actions.listJobsForWorkflowRun({\n  owner:\
          \ context.repo.owner,\n  repo: context.repo.repo,\n  run_id: context.runId\n\
          })).data.jobs[0].html_url + '?pr=' + context.payload.pull_request.number\n\
          \nconst header = await readFile('trusted/ci/check-cherry-picks.md')\nconst\
          \ body = await readFile('checked-cherry-picks.md')\nconst footer =\n  `\\\
          n_Hint: The full diffs are also available in the [runner logs](${job_url})\
          \ with slightly better highlighting._`\n\nconst review = header + body +\
          \ footer\nawait writeFile('review.md', review)\ncore.summary.addRaw(review)\n\
          core.summary.write()\n"
    - name: Request changes
      if: ${{ github.event_name == 'pull_request_target' && steps.check.outcome ==
        'failure' }}
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: "const { readFile } = require('node:fs/promises')\nconst body = await\
          \ readFile('review.md', 'utf-8')\n\nconst pendingReview = (await github.paginate(github.rest.pulls.listReviews,\
          \ {\n  owner: context.repo.owner,\n  repo: context.repo.repo,\n  pull_number:\
          \ context.payload.pull_request.number\n})).find(review =>\n  review.user.login\
          \ == 'github-actions[bot]' && (\n    // If a review is still pending, we\
          \ can just update this instead\n    // of posting a new one.\n    review.state\
          \ == 'CHANGES_REQUESTED' ||\n    // No need to post a new review, if an\
          \ older one with the exact\n    // same content had already been dismissed.\n\
          \    review.body == body\n  )\n)\n\n// Either of those two requests could\
          \ fail for very long comments. This can only happen\n// with multiple commits\
          \ all hitting the truncation limit for the diff. If you ever hit\n// this\
          \ case, consider just splitting up those commits into multiple PRs.\nif\
          \ (pendingReview) {\n  await github.rest.pulls.updateReview({\n    owner:\
          \ context.repo.owner,\n    repo: context.repo.repo,\n    pull_number: context.payload.pull_request.number,\n\
          \    review_id: pendingReview.id,\n    body\n  })\n} else {\n  await github.rest.pulls.createReview({\n\
          \    owner: context.repo.owner,\n    repo: context.repo.repo,\n    pull_number:\
          \ context.payload.pull_request.number,\n    event: 'REQUEST_CHANGES',\n\
          \    body\n  })\n}\n"
    - name: Dismiss old reviews
      if: ${{ github.event_name == 'pull_request_target' && steps.check.outcome ==
        'success' }}
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: "await Promise.all(\n  (await github.paginate(github.rest.pulls.listReviews,\
          \ {\n    owner: context.repo.owner,\n    repo: context.repo.repo,\n    pull_number:\
          \ context.payload.pull_request.number\n  })).filter(review =>\n    review.user.login\
          \ == 'github-actions[bot]'\n  ).map(async (review) => {\n    if (review.state\
          \ == 'CHANGES_REQUESTED') {\n      await github.rest.pulls.dismissReview({\n\
          \        owner: context.repo.owner,\n        repo: context.repo.repo,\n\
          \        pull_number: context.payload.pull_request.number,\n        review_id:\
          \ review.id,\n        message: 'All cherry-picks are good now, thank you!'\n\
          \      })\n    }\n    await github.graphql(`mutation($node_id:ID!) {\n \
          \     minimizeComment(input: {\n        classifier: RESOLVED,\n        subjectId:\
          \ $node_id\n      })\n      { clientMutationId }\n    }`, { node_id: review.node_id\
          \ })\n  })\n)\n"
    - name: Log current API rate limits
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh api /rate_limit | jq
