name: Check shell
on:
  pull_request_target: null
permissions: {}
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/merge
    - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b
    - name: Build shell
      run: nix-build shell.nix
  aarch64-darwin:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/merge
    - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b
    - name: Build shell
      run: nix-build shell.nix
