name: Check
on:
  workflow_call:
    inputs:
      baseBranch:
        required: false
        type: string
      headBranch:
        required: false
        type: string
      mergedSha:
        required: true
        type: string
      targetSha:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN_GHA:
        required: false
permissions: {}
defaults:
  run:
    shell: bash
jobs:
  commits:
    if: inputs.baseBranch && inputs.headBranch
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      with:
        persist-credentials: false
        path: trusted
        sparse-checkout: 'ci/github-script

          '
    - name: Install dependencies
      run: npm install bottleneck
    - name: Log current API rate limits
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh api /rate_limit | jq
    - name: Check commits
      id: check
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        TARGETS_STABLE: ${{ fromJSON(inputs.baseBranch).stable && !contains(fromJSON(inputs.headBranch).type,
          'development') }}
      with:
        script: "const targetsStable = JSON.parse(process.env.TARGETS_STABLE)\nrequire('./trusted/ci/github-script/commits.js')({\n\
          \  github,\n  context,\n  core,\n  dry: context.eventName == 'pull_request',\n\
          \  cherryPicks: context.eventName == 'pull_request' || targetsStable,\n\
          })\n"
    - name: Log current API rate limits
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh api /rate_limit | jq
  owners:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      with:
        persist-credentials: false
        sparse-checkout: .github/actions
    - name: Checkout merge and target commits
      uses: ./.github/actions/checkout
      with:
        merged-as-untrusted-at: ${{ inputs.mergedSha }}
        target-as-trusted-at: ${{ inputs.targetSha }}
    - uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd
    - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad
      continue-on-error: true
      with:
        name: ${{ vars.CACHIX_NAME || 'nixpkgs-gha' }}
        extraPullNames: nixpkgs-gha
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN_GHA }}
        pushFilter: -source$
    - name: Build codeowners validator
      run: nix-build nixpkgs/trusted/ci --arg nixpkgs ./nixpkgs/trusted-pinned -A
        codeownersValidator
    - name: Validate codeowners
      env:
        OWNERS_FILE: nixpkgs/untrusted/ci/OWNERS
        REPOSITORY_PATH: nixpkgs/untrusted
        CHECKS: duppatterns,files,syntax
        EXPERIMENTAL_CHECKS: avoid-shadowing
      run: result/bin/codeowners-validator
