name: Codeowners v2
on:
  pull_request:
    paths:
    - .github/workflows/codeowners-v2.yml
  pull_request_target:
    types:
    - opened
    - ready_for_review
    - synchronize
    - reopened
concurrency:
  group: codeowners-${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number
    || github.run_id }}
  cancel-in-progress: true
permissions: {}
defaults:
  run:
    shell: bash
env:
  OWNERS_FILE: ci/OWNERS
  DRY_MODE: ${{ github.event.pull_request.draft && '1' || '' }}
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        sparse-checkout: .github/actions
    - name: Check if the PR can be merged and checkout the merge and target commits
      uses: ./.github/actions/get-merge-commit
      with:
        merged-as-untrusted: true
        target-as-trusted: true
    - uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba
    - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad
      with:
        name: nixpkgs-ci
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Build codeowners validator
      run: nix-build trusted/ci -A codeownersValidator
    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e
      if: github.event_name == 'pull_request_target' && vars.OWNER_RO_APP_ID
      id: app-token
      with:
        app-id: ${{ vars.OWNER_RO_APP_ID }}
        private-key: ${{ secrets.OWNER_RO_APP_PRIVATE_KEY }}
        permission-administration: read
        permission-members: read
    - name: Log current API rate limits
      if: steps.app-token.outputs.token
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: gh api /rate_limit | jq
    - name: Validate codeowners
      if: steps.app-token.outputs.token
      env:
        OWNERS_FILE: untrusted/${{ env.OWNERS_FILE }}
        GITHUB_ACCESS_TOKEN: ${{ steps.app-token.outputs.token }}
        REPOSITORY_PATH: untrusted
        OWNER_CHECKER_REPOSITORY: ${{ github.repository }}
        EXPERIMENTAL_CHECKS: avoid-shadowing
      run: result/bin/codeowners-validator
    - name: Log current API rate limits
      if: steps.app-token.outputs.token
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: gh api /rate_limit | jq
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        path: trusted
    - name: Build review request package
      run: nix-build trusted/ci -A requestReviews
    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e
      if: github.event_name == 'pull_request_target' && vars.OWNER_APP_ID
      id: app-token
      with:
        app-id: ${{ vars.OWNER_APP_ID }}
        private-key: ${{ secrets.OWNER_APP_PRIVATE_KEY }}
        permission-administration: read
        permission-members: read
        permission-pull-requests: write
    - name: Log current API rate limits
      if: steps.app-token.outputs.token
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: gh api /rate_limit | jq
    - name: Request reviews
      if: steps.app-token.outputs.token
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: result/bin/request-code-owner-reviews.sh ${{ github.repository }} ${{ github.event.number
        }} "$OWNERS_FILE"
    - name: Log current API rate limits
      if: steps.app-token.outputs.token
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: gh api /rate_limit | jq
