name: Dismissed review
on:
  workflow_run:
    workflows:
    - Review dismissed
    types:
    - completed
concurrency:
  group: dismissed-review-${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number
    || github.run_id }}
  cancel-in-progress: true
permissions:
  pull-requests: write
defaults:
  run:
    shell: bash
jobs:
  minimize:
    name: Minimize as resolved
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: "// PRs from forks don't have any PRs associated by default.\n// Thus,\
          \ we request the PR number with an API call *to* the fork's repo.\n// Multiple\
          \ pull requests can be open from the same head commit, either via\n// different\
          \ base branches or head branches.\nconst { head_repository, head_sha, repository\
          \ } = context.payload.workflow_run\nawait Promise.all(\n  (await github.paginate(github.rest.repos.listPullRequestsAssociatedWithCommit,\
          \ {\n    owner: head_repository.owner.login,\n    repo: head_repository.name,\n\
          \    commit_sha: head_sha\n  }))\n  .filter(pull_request => pull_request.base.repo.id\
          \ == repository.id)\n  .map(async (pull_request) =>\n    Promise.all(\n\
          \      (await github.paginate(github.rest.pulls.listReviews, {\n       \
          \ owner: context.repo.owner,\n        repo: context.repo.repo,\n       \
          \ pull_number: pull_request.number\n      })).filter(review =>\n       \
          \ review.user.login == 'github-actions[bot]' &&\n        review.state ==\
          \ 'DISMISSED'\n      ).map(review => github.graphql(`\n        mutation($node_id:ID!)\
          \ {\n          minimizeComment(input: {\n            classifier: RESOLVED,\n\
          \            subjectId: $node_id\n          })\n          { clientMutationId\
          \ }\n        }`,\n        { node_id: review.node_id }\n      ))\n    )\n\
          \  )\n)\n"
