name: Dismissed Review
on:
  pull_request_review:
    types:
    - dismissed
permissions:
  pull-requests: write
jobs:
  minimize:
    name: Minimize as resolved
    if: github.event.review.user.login == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: "await github.graphql(`mutation($node_id:ID!) {\n  minimizeComment(input:\
          \ {\n    classifier: RESOLVED,\n    subjectId: $node_id\n  })\n  { clientMutationId\
          \ }\n}`, { node_id: context.payload.review.node_id })\n"
