name: Eval
on:
  pull_request:
    paths:
    - .github/workflows/eval.yml
    - .github/workflows/reviews.yml
  pull_request_target: null
  push:
    branches:
    - master
    - staging
    - release-*
    - staging-*
    - haskell-updates
    - python-updates
permissions: {}
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      mergedSha: ${{ steps.get-merge-commit.outputs.mergedSha }}
      targetSha: ${{ steps.get-merge-commit.outputs.targetSha }}
      systems: ${{ steps.systems.outputs.systems }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        sparse-checkout: '.github/actions

          ci/supportedSystems.json

          '
    - name: Check if the PR can be merged and get the test merge commit
      uses: ./.github/actions/get-merge-commit
      id: get-merge-commit
    - name: Load supported systems
      id: systems
      run: 'echo "systems=$(jq -c <ci/supportedSystems.json)" >> "$GITHUB_OUTPUT"

        '
  outpaths:
    name: Outpaths
    runs-on: ubuntu-latest
    needs:
    - prepare
    strategy:
      fail-fast: false
      matrix:
        system: ${{ fromJSON(needs.prepare.outputs.systems) }}
    steps:
    - name: Enable swap
      run: 'sudo fallocate -l 10G /swap

        sudo chmod 600 /swap

        sudo mkswap /swap

        sudo swapon /swap

        '
    - name: Check out the PR at the test merge commit
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ needs.prepare.outputs.mergedSha }}
        path: untrusted
    - name: Install Nix
      uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
      with:
        extra_nix_config: sandbox = true
    - name: Evaluate the ${{ matrix.system }} output paths for all derivation attributes
      env:
        MATRIX_SYSTEM: ${{ matrix.system }}
      run: "nix-build untrusted/ci -A eval.singleSystem \\\n  --argstr evalSystem\
        \ \"$MATRIX_SYSTEM\" \\\n  --arg chunkSize 10000 \\\n  --out-link merged\n\
        # If it uses too much memory, slightly decrease chunkSize\n"
    - name: Upload the output paths and eval stats
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: merged-${{ matrix.system }}
        path: merged/*
    - name: Get target run id
      if: needs.prepare.outputs.targetSha
      id: targetRunId
      env:
        GH_TOKEN: ${{ github.token }}
        MATRIX_SYSTEM: ${{ matrix.system }}
        REPOSITORY: ${{ github.repository }}
        TARGET_SHA: ${{ needs.prepare.outputs.targetSha }}
      run: "# Get the latest eval.yml workflow run for the PR's target commit\nif\
        \ ! run=$(gh api --method GET /repos/\"$REPOSITORY\"/actions/workflows/eval.yml/runs\
        \ \\\n  -f head_sha=\"$TARGET_SHA\" -f event=push \\\n  --jq '.workflow_runs\
        \ | sort_by(.run_started_at) | .[-1]') \\\n  || [[ -z \"$run\" ]]; then\n\
        \  echo \"Could not find an eval.yml workflow run for $TARGET_SHA, cannot\
        \ make comparison\"\n  exit 1\nfi\necho \"Comparing against $(jq .html_url\
        \ <<< \"$run\")\"\nrunId=$(jq .id <<< \"$run\")\n\nif ! job=$(gh api --method\
        \ GET /repos/\"$REPOSITORY\"/actions/runs/\"$runId\"/jobs \\\n  --jq \".jobs[]\
        \ | select (.name == \\\"Outpaths ($MATRIX_SYSTEM)\\\")\") \\\n  || [[ -z\
        \ \"$job\" ]]; then\n  echo \"Could not find the Outpaths ($MATRIX_SYSTEM)\
        \ job for workflow run $runId, cannot make comparison\"\n  exit 1\nfi\njobId=$(jq\
        \ .id <<< \"$job\")\nconclusion=$(jq -r .conclusion <<< \"$job\")\n\nwhile\
        \ [[ \"$conclusion\" == null || \"$conclusion\" == \"\" ]]; do\n  echo \"\
        Job not done, waiting 10 seconds before checking again\"\n  sleep 10\n  conclusion=$(gh\
        \ api /repos/\"$REPOSITORY\"/actions/jobs/\"$jobId\" --jq '.conclusion')\n\
        done\n\nif [[ \"$conclusion\" != \"success\" ]]; then\n  echo \"Job was not\
        \ successful (conclusion: $conclusion), cannot make comparison\"\n  exit 1\n\
        fi\n\necho \"targetRunId=$runId\" >> \"$GITHUB_OUTPUT\"\n"
    - uses: actions/download-artifact@v4
      if: steps.targetRunId.outputs.targetRunId
      with:
        run-id: ${{ steps.targetRunId.outputs.targetRunId }}
        name: merged-${{ matrix.system }}
        path: target
        github-token: ${{ github.token }}
        merge-multiple: true
    - name: Compare outpaths against the target branch
      if: steps.targetRunId.outputs.targetRunId
      env:
        MATRIX_SYSTEM: ${{ matrix.system }}
      run: "nix-build untrusted/ci -A eval.diff \\\n  --arg beforeDir ./target \\\n\
        \  --arg afterDir \"$(readlink ./merged)\" \\\n  --argstr evalSystem \"$MATRIX_SYSTEM\"\
        \ \\\n  --out-link diff\n"
    - name: Upload outpaths diff and stats
      if: steps.targetRunId.outputs.targetRunId
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: diff-${{ matrix.system }}
        path: diff/*
  compare:
    name: Comparison
    runs-on: ubuntu-latest
    needs:
    - prepare
    - outpaths
    if: needs.prepare.outputs.targetSha
    permissions:
      issues: write
      pull-requests: write
      statuses: write
    steps:
    - name: Download output paths and eval stats for all systems
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
      with:
        pattern: diff-*
        path: diff
        merge-multiple: true
    - name: Check out the PR at the target commit
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ needs.prepare.outputs.targetSha }}
        path: trusted
    - name: Install Nix
      uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
      with:
        extra_nix_config: sandbox = true
    - name: Combine all output paths and eval stats
      run: "nix-build trusted/ci -A eval.combine \\\n  --arg diffDir ./diff \\\n \
        \ --out-link combined\n"
    - name: Compare against the target branch
      env:
        AUTHOR_ID: ${{ github.event.pull_request.user.id }}
      run: "git -C trusted fetch --depth 1 origin ${{ needs.prepare.outputs.mergedSha\
        \ }}\ngit -C trusted diff --name-only ${{ needs.prepare.outputs.mergedSha\
        \ }} \\\n  | jq --raw-input --slurp 'split(\"\\n\")[:-1]' > touched-files.json\n\
        \n# Use the target branch to get accurate maintainer info\nnix-build trusted/ci\
        \ -A eval.compare \\\n  --arg combinedDir \"$(realpath ./combined)\" \\\n\
        \  --arg touchedFilesJson ./touched-files.json \\\n  --argstr githubAuthorId\
        \ \"$AUTHOR_ID\" \\\n  --out-link comparison\n\ncat comparison/step-summary.md\
        \ >> \"$GITHUB_STEP_SUMMARY\"\n"
    - name: Upload the comparison results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      with:
        name: comparison
        path: comparison/*
    - name: Labelling pull request
      if: ${{ github.event_name == 'pull_request_target' }}
      env:
        GH_TOKEN: ${{ github.token }}
        REPOSITORY: ${{ github.repository }}
        NUMBER: ${{ github.event.number }}
      run: "# Get all currently set labels that we manage\ngh api \\\n  /repos/\"\
        $REPOSITORY\"/issues/\"$NUMBER\"/labels \\\n  --jq '.[].name | select(startswith(\"\
        10.rebuild\") or . == \"11.by: package-maintainer\")' \\\n  | sort > before\n\
        \n# And the labels that should be there\njq -r '.labels[]' comparison/changed-paths.json\
        \ \\\n  | sort > after\n\n# Remove the ones not needed anymore\nwhile read\
        \ -r toRemove; do\n  echo \"Removing label $toRemove\"\n  gh api \\\n    --method\
        \ DELETE \\\n    /repos/\"$REPOSITORY\"/issues/\"$NUMBER\"/labels/\"$toRemove\"\
        \ndone < <(comm -23 before after)\n\n# And add the ones that aren't set already\n\
        while read -r toAdd; do\n  echo \"Adding label $toAdd\"\n  gh api \\\n   \
        \ --method POST \\\n    /repos/\"$REPOSITORY\"/issues/\"$NUMBER\"/labels \\\
        \n    -f \"labels[]=$toAdd\"\ndone < <(comm -13 before after)\n"
    - name: Add eval summary to commit statuses
      if: ${{ github.event_name == 'pull_request_target' }}
      env:
        GH_TOKEN: ${{ github.token }}
        PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        NUMBER: ${{ github.event.number }}
      run: "description=$(jq -r '\n\"Package: added \" + (.attrdiff.added | length\
        \ | tostring) +\n\", removed \" + (.attrdiff.removed | length | tostring)\
        \ +\n\", changed \" + (.attrdiff.changed | length | tostring) +\n\", Rebuild:\
        \ linux \" + (.rebuildCountByKernel.linux | tostring) +\n\", darwin \" + (.rebuildCountByKernel.darwin\
        \ | tostring)\n' <comparison/changed-paths.json)\ntarget_url=\"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID?pr=$NUMBER\"\
        \ngh api --method POST \\\n  -H \"Accept: application/vnd.github+json\" -H\
        \ \"X-GitHub-Api-Version: 2022-11-28\" \\\n  \"/repos/$GITHUB_REPOSITORY/statuses/$PR_HEAD_SHA\"\
        \ \\\n  -f \"context=Eval / Summary\" -f \"state=success\" -f \"description=$description\"\
        \ -f \"target_url=$target_url\"\n"
  reviewers:
    name: Reviewers
    needs:
    - prepare
    - outpaths
    if: needs.prepare.outputs.targetSha
    uses: ./.github/workflows/reviewers.yml
    secrets: inherit
