name: Lint
on:
  workflow_dispatch: {}
permissions: {}
defaults:
  run:
    shell: bash
jobs:
  treefmt:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
        sparse-checkout: .github/actions
    - name: Checkout the merge commit
      uses: ./.github/actions/checkout
      with:
        merged-as-untrusted-at: ${{ inputs.mergedSha }}
    - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15
    - name: Check that files are formatted
      run: "# Note that it's fine to run this on untrusted code because:\n# - There's\
        \ no secrets accessible here\n# - The build is sandboxed\nif ! nix-build nixpkgs/untrusted/ci\
        \ --arg nixpkgs ./nixpkgs/untrusted-pinned -A fmt.check; then\n  echo \"Some\
        \ files are not properly formatted\"\n  echo \"Please format them by going\
        \ to the Nixpkgs root directory and running one of:\"\n  echo \"  nix-shell\
        \ --run treefmt\"\n  echo \"  nix develop --command treefmt\"\n  echo \" \
        \ nix fmt\"\n  echo \"Make sure your branch is up to date with master; rebase\
        \ if not.\"\n  echo \"If you're having trouble, please ping @NixOS/nix-formatting\"\
        \n  exit 1\nfi\n"
  parse:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
        sparse-checkout: .github/actions
    - name: Checkout the merge commit
      uses: ./.github/actions/checkout
      with:
        merged-as-untrusted-at: ${{ inputs.mergedSha }}
    - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15
    - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1
      continue-on-error: true
      with:
        name: ${{ vars.CACHIX_NAME || 'nixpkgs-gha' }}
        extraPullNames: nixpkgs-gha
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN_GHA }}
        pushFilter: -source$
    - name: Parse all nix files
      run: '# Tests multiple versions at once, let''s make sure all of them run, so
        keep-going.

        nix-build nixpkgs/untrusted/ci --arg nixpkgs ./nixpkgs/untrusted-pinned -A
        parse --keep-going

        '
  nixpkgs-vet:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
        sparse-checkout: .github/actions
    - name: Checkout merge and target commits
      uses: ./.github/actions/checkout
      with:
        merged-as-untrusted-at: ${{ inputs.mergedSha }}
        target-as-trusted-at: ${{ inputs.targetSha }}
    - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15
    - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1
      continue-on-error: true
      with:
        name: ${{ vars.CACHIX_NAME || 'nixpkgs-gha' }}
        extraPullNames: nixpkgs-gha
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN_GHA }}
        pushFilter: -source$
    - name: Running nixpkgs-vet
      env:
        CLICOLOR_FORCE: 1
      run: "if nix-build nixpkgs/untrusted/ci --arg nixpkgs ./nixpkgs/untrusted-pinned\
        \ -A nixpkgs-vet --arg base \"./nixpkgs/trusted\" --arg head \"./nixpkgs/untrusted\"\
        ; then\n  exit 0\nelse\n  exitCode=$?\n  echo \"To run locally: ./ci/nixpkgs-vet.sh\
        \ $GITHUB_BASE_REF https://github.com/$GITHUB_REPOSITORY.git\"\n  echo \"\
        If you're having trouble, ping @NixOS/nixpkgs-vet\"\n  exit \"$exitCode\"\n\
        fi\n"
  commits:
    if: ${{ github.event.pull_request.number }}
    runs-on: ubuntu-slim
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
        path: trusted
        sparse-checkout: 'ci/github-script

          '
    - name: Check commit messages
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        script: "const checkCommitMessages = require('./trusted/ci/github-script/lint-commits.js')\n\
          \ncheckCommitMessages({\n  github,\n  context,\n  core,\n})\n"
