name: Merge Group
on:
  merge_group: null
  workflow_call:
    inputs:
      mergedSha:
        required: true
        type: string
      targetSha:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
permissions: {}
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      systems: ${{ steps.systems.outputs.systems }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        sparse-checkout: 'ci/supportedSystems.json

          '
    - name: Load supported systems
      id: systems
      run: 'echo "systems=$(jq -c <ci/supportedSystems.json)" >> "$GITHUB_OUTPUT"

        '
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    with:
      mergedSha: ${{ inputs.mergedSha || github.event.merge_group.head_sha }}
      targetSha: ${{ inputs.targetSha || github.event.merge_group.base_sha }}
  eval:
    name: Eval
    needs:
    - prepare
    uses: ./.github/workflows/eval.yml
    permissions:
      statuses: write
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    with:
      mergedSha: ${{ inputs.mergedSha || github.event.merge_group.head_sha }}
      systems: ${{ needs.prepare.outputs.systems }}
  unlock:
    if: github.event_name != 'pull_request' && always()
    needs:
    - lint
    - eval
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      with:
        script: "const { serverUrl, repo, runId, payload } = context\nconst target_url\
          \ =\n  `${serverUrl}/${repo.owner}/${repo.repo}/actions/runs/${runId}`\n\
          await github.rest.repos.createCommitStatus({\n  ...repo,\n  sha: payload.merge_group.head_sha,\n\
          \  // WARNING:\n  // Do NOT change the name of this, otherwise the rule\
          \ will not catch it anymore.\n  // This would prevent all PRs from merging.\n\
          \  context: 'no PR failures',\n  state: JSON.parse(process.env.RESULTS).every(result\
          \ => result == 'success') ? 'success' : 'error',\n  target_url,\n})\n"
