name: Merge Group
on:
  workflow_dispatch: {}
permissions: {}
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      baseBranch: ${{ steps.prepare.outputs.base }}
      mergedSha: ${{ steps.prepare.outputs.mergedSha }}
      targetSha: ${{ steps.prepare.outputs.targetSha }}
      systems: ${{ steps.prepare.outputs.systems }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
        sparse-checkout: 'ci/supportedSystems.json

          '
    - id: prepare
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        MERGED_SHA: ${{ inputs.mergedSha }}
        TARGET_SHA: ${{ inputs.targetSha }}
      with:
        script: "const { classify } = require('./ci/supportedBranches.js')\nconst\
          \ baseBranch = (\n  context.payload.merge_group?.base_ref ??\n  context.payload.pull_request.base.ref\n\
          ).replace(/^refs\\/heads\\//, '')\nconst baseClassification = classify(baseBranch)\n\
          core.setOutput('base', baseClassification)\ncore.info('base classification:',\
          \ baseClassification)\n\ncore.setOutput('mergedSha', context.payload.merge_group?.head_sha\
          \ ?? process.env.MERGED_SHA)\ncore.info(`mergedSha: ${context.payload.merge_group?.head_sha\
          \ ?? process.env.MERGED_SHA}`)\ncore.setOutput('targetSha', context.payload.merge_group?.base_sha\
          \ ?? process.env.TARGET_SHA)\ncore.info(`targetSha: ${context.payload.merge_group?.base_sha\
          \ ?? process.env.TARGET_SHA}`)\ncore.setOutput('systems', require('./ci/supportedSystems.json'))\n"
  check:
    name: Check
    needs:
    - prepare
    uses: ./.github/workflows/check.yml
    permissions:
      pull-requests: write
    secrets:
      CACHIX_AUTH_TOKEN_GHA: ${{ secrets.CACHIX_AUTH_TOKEN_GHA }}
    with:
      mergedSha: ${{ needs.prepare.outputs.mergedSha }}
      targetSha: ${{ needs.prepare.outputs.targetSha }}
  lint:
    name: Lint
    needs:
    - prepare
    uses: ./.github/workflows/lint.yml
    secrets:
      CACHIX_AUTH_TOKEN_GHA: ${{ secrets.CACHIX_AUTH_TOKEN_GHA }}
    with:
      mergedSha: ${{ needs.prepare.outputs.mergedSha }}
      targetSha: ${{ needs.prepare.outputs.targetSha }}
  eval:
    name: Eval
    needs:
    - prepare
    uses: ./.github/workflows/eval.yml
    permissions:
      pull-requests: write
      statuses: write
    secrets:
      CACHIX_AUTH_TOKEN_GHA: ${{ secrets.CACHIX_AUTH_TOKEN_GHA }}
    with:
      artifact-prefix: ${{ inputs.artifact-prefix }}
      mergedSha: ${{ needs.prepare.outputs.mergedSha }}
      targetSha: ${{ needs.prepare.outputs.targetSha }}
      systems: ${{ needs.prepare.outputs.systems }}
  build:
    name: Build
    needs:
    - prepare
    uses: ./.github/workflows/build.yml
    secrets:
      CACHIX_AUTH_TOKEN_GHA: ${{ secrets.CACHIX_AUTH_TOKEN_GHA }}
    with:
      artifact-prefix: ${{ inputs.artifact-prefix }}
      baseBranch: ${{ needs.prepare.outputs.baseBranch }}
      mergedSha: ${{ needs.prepare.outputs.mergedSha }}
      targetSha: ${{ needs.prepare.outputs.targetSha }}
  unlock:
    if: github.event_name != 'pull_request' && always()
    needs:
    - check
    - lint
    - eval
    - build
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      with:
        script: "const { serverUrl, repo, runId, payload } = context\nconst target_url\
          \ =\n  `${serverUrl}/${repo.owner}/${repo.repo}/actions/runs/${runId}`\n\
          await github.rest.repos.createCommitStatus({\n  ...repo,\n  sha: payload.merge_group.head_sha,\n\
          \  // WARNING:\n  // Do NOT change the name of this, otherwise the rule\
          \ will not catch it anymore.\n  // This would prevent all PRs from merging.\n\
          \  context: 'no PR failures',\n  state: JSON.parse(process.env.RESULTS).every(result\
          \ => result == 'success') ? 'success' : 'error',\n  target_url,\n})\n"
