name: Vet nixpkgs
on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - edited
permissions: {}
jobs:
  get-merge-commit:
    uses: ./.github/workflows/get-merge-commit.yml
  check:
    name: nixpkgs-vet
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: get-merge-commit
    if: needs.get-merge-commit.outputs.mergedSha
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        ref: ${{ needs.get-merge-commit.outputs.mergedSha }}
        fetch-depth: 2
    - name: Checking out target branch
      run: 'target=$(mktemp -d)

        git worktree add "$target" "$(git rev-parse HEAD^1)"

        echo "target=$target" >> "$GITHUB_ENV"

        '
    - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
    - name: Fetching the pinned tool
      run: "# The pinned version of the tooling to use.\ntoolVersion=$(<ci/nixpkgs-vet/pinned-version.txt)\n\
        \n# Fetch the x86_64-linux-specific release artifact containing the gzipped\
        \ NAR of the pre-built tool.\ntoolPath=$(curl -sSfL https://github.com/NixOS/nixpkgs-vet/releases/download/\"\
        $toolVersion\"/x86_64-linux.nar.gz \\\n  | gzip -cd | nix-store --import |\
        \ tail -1)\n\n# Adds a result symlink as a GC root.\nnix-store --realise \"\
        $toolPath\" --add-root result\n"
    - name: Running nixpkgs-vet
      env:
        CLICOLOR_FORCE: 1
      run: "if result/bin/nixpkgs-vet --base \"$target\" .; then\n  exit 0\nelse\n\
        \  exitCode=$?\n  echo \"To run locally: ./ci/nixpkgs-vet.sh $GITHUB_BASE_REF\
        \ https://github.com/$GITHUB_REPOSITORY.git\"\n  echo \"If you're having trouble,\
        \ ping @NixOS/nixpkgs-vet\"\n  exit \"$exitCode\"\nfi\n"
