name: Vet nixpkgs
on:
  pull_request:
    paths:
    - .github/workflows/nixpkgs-vet.yml
  pull_request_target: null
permissions: {}
jobs:
  check:
    name: nixpkgs-vet
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        sparse-checkout: .github/actions
    - name: Check if the PR can be merged and checkout merged and target commits
      uses: ./.github/actions/get-merge-commit
      with:
        merged-as-untrusted: true
        target-as-trusted: true
    - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
    - name: Running nixpkgs-vet
      env:
        CLICOLOR_FORCE: 1
      run: "if nix-build untrusted/ci -A nixpkgs-vet --arg base \"./trusted\" --arg\
        \ head \"./untrusted\"; then\n  exit 0\nelse\n  exitCode=$?\n  echo \"To run\
        \ locally: ./ci/nixpkgs-vet.sh $GITHUB_BASE_REF https://github.com/$GITHUB_REPOSITORY.git\"\
        \n  echo \"If you're having trouble, ping @NixOS/nixpkgs-vet\"\n  exit \"\
        $exitCode\"\nfi\n"
