name: Periodic Merges (24h)
on:
  workflow_dispatch: {}
permissions: {}
defaults:
  run:
    shell: bash
jobs:
  periodic-merge:
    if: github.repository_owner == 'NixOS'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        pairs:
        - from: release-25.11
          into: staging-next-25.11
        - from: staging-next-25.11
          into: staging-25.11
        - name: "merge-base(master,staging) \u2192 haskell-updates"
          from: master staging
          into: haskell-updates
    uses: ./.github/workflows/periodic-merge.yml
    with:
      from: ${{ matrix.pairs.from }}
      into: ${{ matrix.pairs.into }}
    name: "${{ matrix.pairs.name || format('{0} \u2192 {1}', matrix.pairs.from, matrix.pairs.into)\
      \ }}"
    secrets:
      NIXPKGS_CI_APP_PRIVATE_KEY: ${{ secrets.NIXPKGS_CI_APP_PRIVATE_KEY }}
