name: Periodic Merges (6h)
on:
  workflow_dispatch: {}
permissions: {}
defaults:
  run:
    shell: bash
jobs:
  periodic-merge:
    if: github.repository_owner == 'NixOS'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        pairs:
        - from: master
          into: staging-next
        - from: staging-next
          into: staging
        - from: master
          into: staging-nixos
    uses: ./.github/workflows/periodic-merge.yml
    with:
      from: ${{ matrix.pairs.from }}
      into: ${{ matrix.pairs.into }}
    name: "${{ format('{0} \u2192 {1}', matrix.pairs.from, matrix.pairs.into) }}"
    secrets:
      NIXPKGS_CI_APP_PRIVATE_KEY: ${{ secrets.NIXPKGS_CI_APP_PRIVATE_KEY }}
