name: PR
on:
  pull_request_target: null
  workflow_call:
    inputs:
      artifact-prefix:
        required: true
        type: string
    secrets:
      NIXPKGS_CI_APP_PRIVATE_KEY:
        required: true
concurrency:
  group: pr-${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number
    || github.run_id }}
  cancel-in-progress: true
permissions: {}
jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      baseBranch: ${{ steps.prepare.outputs.base }}
      headBranch: ${{ steps.prepare.outputs.head }}
      mergedSha: ${{ steps.prepare.outputs.mergedSha }}
      targetSha: ${{ steps.prepare.outputs.targetSha }}
      systems: ${{ steps.prepare.outputs.systems }}
      touched: ${{ steps.prepare.outputs.touched }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
        sparse-checkout-cone-mode: true
        sparse-checkout: 'ci/github-script

          '
    - id: prepare
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        retries: 10
        retry-exempt-status-codes: 400,401,403,404
        script: "require('./ci/github-script/prepare.js')({\n  github,\n  context,\n\
          \  core,\n  dry: context.eventName == 'pull_request',\n})\n"
  check:
    name: Check
    needs:
    - prepare
    uses: ./.github/workflows/check.yml
    permissions:
      pull-requests: write
    with:
      baseBranch: ${{ needs.prepare.outputs.baseBranch }}
      headBranch: ${{ needs.prepare.outputs.headBranch }}
      mergedSha: ${{ needs.prepare.outputs.mergedSha }}
      targetSha: ${{ needs.prepare.outputs.targetSha }}
  lint:
    name: Lint
    needs:
    - prepare
    uses: ./.github/workflows/lint.yml
    with:
      mergedSha: ${{ needs.prepare.outputs.mergedSha }}
      targetSha: ${{ needs.prepare.outputs.targetSha }}
  eval:
    name: Eval
    needs:
    - prepare
    uses: ./.github/workflows/eval.yml
    permissions:
      pull-requests: write
      statuses: write
    with:
      artifact-prefix: ${{ inputs.artifact-prefix }}
      mergedSha: ${{ needs.prepare.outputs.mergedSha }}
      headSha: ${{ github.event.pull_request.head.sha }}
      targetSha: ${{ needs.prepare.outputs.targetSha }}
      systems: ${{ needs.prepare.outputs.systems }}
      testVersions: ${{ contains(fromJSON(needs.prepare.outputs.touched), 'pinned')
        && !contains(fromJSON(needs.prepare.outputs.headBranch).type, 'development')
        }}
  bot:
    name: Bot
    needs:
    - prepare
    - eval
    uses: ./.github/workflows/bot.yml
    permissions:
      issues: write
      pull-requests: write
    secrets:
      NIXPKGS_CI_APP_PRIVATE_KEY: ${{ secrets.NIXPKGS_CI_APP_PRIVATE_KEY }}
    with:
      headBranch: ${{ needs.prepare.outputs.headBranch }}
  build:
    name: Build
    needs:
    - prepare
    uses: ./.github/workflows/build.yml
    with:
      artifact-prefix: ${{ inputs.artifact-prefix }}
      baseBranch: ${{ needs.prepare.outputs.baseBranch }}
      mergedSha: ${{ needs.prepare.outputs.mergedSha }}
      targetSha: ${{ needs.prepare.outputs.targetSha }}
  unlock:
    if: github.event_name != 'pull_request' && always()
    needs:
    - check
    - lint
    - eval
    - build
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        RESULTS: ${{ toJSON(needs.*.result) }}
      with:
        script: "const { serverUrl, repo, runId, payload } = context\nconst target_url\
          \ =\n  `${serverUrl}/${repo.owner}/${repo.repo}/actions/runs/${runId}?pr=${payload.pull_request.number}`\n\
          await github.rest.repos.createCommitStatus({\n  ...repo,\n  sha: payload.pull_request.head.sha,\n\
          \  // WARNING:\n  // Do NOT change the name of this, otherwise the rule\
          \ will not catch it anymore.\n  // This would prevent all PRs from merging.\n\
          \  context: 'no PR failures',\n  state: JSON.parse(process.env.RESULTS).every(status\
          \ => status == 'success') ? 'success' : 'error',\n  target_url,\n})\n"
