name: Push
on:
  pull_request:
    paths:
    - .github/workflows/push.yml
  push:
    branches:
    - master
    - staging
    - release-*
    - staging-*
    - haskell-updates
    - python-updates
permissions: {}
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      systems: ${{ steps.systems.outputs.systems }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        sparse-checkout: 'ci/supportedSystems.json

          '
    - name: Load supported systems
      id: systems
      run: 'echo "systems=$(jq -c <ci/supportedSystems.json)" >> "$GITHUB_OUTPUT"

        '
  eval:
    name: Eval
    needs:
    - prepare
    uses: ./.github/workflows/eval.yml
    permissions:
      issues: write
      pull-requests: write
      statuses: write
    with:
      mergedSha: ${{ github.sha }}
      systems: ${{ needs.prepare.outputs.systems }}
