name: Review
on:
  workflow_run:
    workflows:
    - Reviewed
    types:
    - completed
permissions:
  pull-requests: write
defaults:
  run:
    shell: bash
jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      with:
        persist-credentials: false
        sparse-checkout: 'ci/github-script

          '
    - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94
      if: github.event_name != 'pull_request' && vars.NIXPKGS_CI_APP_ID
      id: app-token
      with:
        app-id: ${{ vars.NIXPKGS_CI_APP_ID }}
        private-key: ${{ secrets.NIXPKGS_CI_APP_PRIVATE_KEY }}
        permission-pull-requests: write
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{ steps.app-token.outputs.token || github.token }}
        retries: 3
        script: "const { handleMergeComment } = require('./ci/github-script/merge.js')\n\
          \n// PRs from forks don't have any PRs associated by default.\n// Thus,\
          \ we request the PR number with an API call *to* the fork's repo.\n// Multiple\
          \ pull requests can be open from the same head commit, either via\n// different\
          \ base branches or head branches.\nconst { head_repository, head_sha, repository\
          \ } = context.payload.workflow_run\nawait Promise.all(\n  (await github.paginate(github.rest.repos.listPullRequestsAssociatedWithCommit,\
          \ {\n    owner: head_repository.owner.login,\n    repo: head_repository.name,\n\
          \    commit_sha: head_sha\n  }))\n  .filter(pull_request => pull_request.base.repo.id\
          \ == repository.id)\n  .map(async (pull_request) =>\n    Promise.all(\n\
          \      (await github.paginate(github.rest.pulls.listReviews, {\n       \
          \ owner: context.repo.owner,\n        repo: context.repo.repo,\n       \
          \ pull_number: pull_request.number\n      })).map(review => {\n        //\
          \ The `check` workflow creates review comments which reviewers\n       \
          \ // are encouraged to manually dismiss if they're not relevant.\n     \
          \   // When a CI-generated review is dismissed, this job automatically minimizes\n\
          \        // it, preventing it from cluttering the PR.\n        if (review.user?.login\
          \ == 'github-actions[bot]' && review.state == 'DISMISSED')\n          return\
          \ github.graphql(`\n            mutation($node_id:ID!) {\n             \
          \ minimizeComment(input: {\n                classifier: RESOLVED,\n    \
          \            subjectId: $node_id\n              })\n              { clientMutationId\
          \ }\n            }`,\n            { node_id: review.node_id }\n        \
          \  )\n\n        // The `bot` workflow reacts to comments with @NixOS/nixpkgs-merge-bot\
          \ references, but might only\n        // pick up a comment after up to 10\
          \ minutes. To give the user instant feedback, this job adds\n        //\
          \ a reaction to these comments.\n        return handleMergeComment({\n \
          \         github,\n          body: review.body,\n          node_id: review.node_id,\n\
          \          reaction: 'EYES',\n        })\n      })\n    )\n  )\n)\n"
