name: Reviewers
on:
  pull_request:
    paths:
    - .github/workflows/reviewers.yml
  pull_request_target:
    types:
    - ready_for_review
  workflow_call:
    inputs:
      caller:
        description: Name of the calling workflow.
        required: true
        type: string
concurrency:
  group: ${{ inputs.caller }}-${{ github.workflow }}-${{ github.event_name }}-${{
    github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions: {}
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
    - name: Check out the PR at the base commit
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        path: trusted
        sparse-checkout: ci
    - name: Install Nix
      uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641
      with:
        extra_nix_config: sandbox = true
    - name: Build the requestReviews derivation
      run: nix-build trusted/ci -A requestReviews
    - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e
      if: vars.OWNER_APP_ID
      id: app-token
      with:
        app-id: ${{ vars.OWNER_APP_ID }}
        private-key: ${{ secrets.OWNER_APP_PRIVATE_KEY }}
        permission-administration: read
        permission-members: read
        permission-pull-requests: write
    - name: Wait for comparison to be done
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
      with:
        script: "const run_id = (await github.rest.actions.listWorkflowRuns({\n  owner:\
          \ context.repo.owner,\n  repo: context.repo.repo,\n  workflow_id: 'eval.yml',\n\
          \  event: context.eventName,\n  head_sha: context.payload.pull_request.head.sha\n\
          })).data.workflow_runs[0].id\n\n// Waiting 120 * 5 sec = 10 min. max.\n\
          // The extreme case is an Eval run that just started when the PR is undrafted.\n\
          // Eval takes max 5-6 minutes, normally.\nfor (let i = 0; i < 120; i++)\
          \ {\n  const result = await github.rest.actions.listWorkflowRunArtifacts({\n\
          \    owner: context.repo.owner,\n    repo: context.repo.repo,\n    run_id,\n\
          \    name: 'comparison'\n  })\n  if (result.data.total_count > 0) return\n\
          \  await new Promise(resolve => setTimeout(resolve, 5000))\n}\nthrow new\
          \ Error(\"No comparison artifact found.\")\n"
    - name: Download the comparison results
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
      with:
        pattern: comparison
        path: comparison
        merge-multiple: true
    - name: Requesting maintainer reviews
      if: ${{ steps.app-token.outputs.token }}
      env:
        GH_TOKEN: ${{ github.token }}
        REPOSITORY: ${{ github.repository }}
        NUMBER: ${{ github.event.number }}
        AUTHOR: ${{ github.event.pull_request.user.login }}
        DRY_MODE: ${{ github.event.pull_request.draft && '1' || '' }}
      run: "# maintainers.json contains GitHub IDs. Look up handles to request reviews\
        \ from.\n# There appears to be no API to request reviews based on GitHub IDs\n\
        jq -r 'keys[]' comparison/maintainers.json \\\n  | while read -r id; do gh\
        \ api /user/\"$id\" --jq .login; done \\\n  | GH_TOKEN=${{ steps.app-token.outputs.token\
        \ }} result/bin/request-reviewers.sh \"$REPOSITORY\" \"$NUMBER\" \"$AUTHOR\"\
        \n"
