name: Test
on:
  pull_request: null
concurrency:
  group: test-${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number
    || github.run_id }}
  cancel-in-progress: true
permissions: {}
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      merge-group: ${{ steps.files.outputs.merge-group }}
      mergedSha: ${{ steps.prepare.outputs.mergedSha }}
      pr: ${{ steps.files.outputs.pr }}
      push: ${{ steps.files.outputs.push }}
      targetSha: ${{ steps.prepare.outputs.targetSha }}
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
      with:
        persist-credentials: false
        sparse-checkout-cone-mode: true
        sparse-checkout: 'ci/github-script

          '
    - id: prepare
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        retries: 10
        retry-exempt-status-codes: 400,401,403,404
        script: "require('./ci/github-script/prepare.js')({\n  github,\n  context,\n\
          \  core,\n  // Review comments will be posted by the main PR workflow on\
          \ the pull_request_target event.\n  dry: false,\n})\n"
    - name: Determine changed files
      id: files
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        script: "const files = (await github.paginate(github.rest.pulls.listFiles,\
          \ {\n  ...context.repo,\n  pull_number: context.payload.pull_request.number,\n\
          \  per_page: 100,\n})).map(file => file.filename)\n\nif (files.some(file\
          \ => [\n  '.github/workflows/eval.yml',\n  '.github/workflows/lint.yml',\n\
          \  '.github/workflows/merge-group.yml',\n  '.github/workflows/test.yml',\n\
          ].includes(file))) core.setOutput('merge-group', true)\n\nif (files.some(file\
          \ => [\n  '.github/actions/checkout/action.yml',\n  '.github/workflows/bot.yml',\n\
          \  '.github/workflows/build.yml',\n  '.github/workflows/check.yml',\n  '.github/workflows/eval.yml',\n\
          \  '.github/workflows/lint.yml',\n  '.github/workflows/pull-request-target.yml',\n\
          \  '.github/workflows/test.yml',\n  'ci/github-script/bot.js',\n  'ci/github-script/merge.js',\n\
          \  'ci/github-script/withRateLimit.js',\n].includes(file))) core.setOutput('pr',\
          \ true)\n"
  merge-group:
    if: needs.prepare.outputs.merge-group
    name: Merge Group
    needs:
    - prepare
    uses: ./.github/workflows/merge-group.yml
    permissions:
      pull-requests: write
      statuses: write
    with:
      artifact-prefix: mg-
      mergedSha: ${{ needs.prepare.outputs.mergedSha }}
      targetSha: ${{ needs.prepare.outputs.targetSha }}
  pr:
    if: needs.prepare.outputs.pr
    name: PR
    needs:
    - prepare
    uses: ./.github/workflows/pull-request-target.yml
    permissions:
      issues: write
      pull-requests: write
      statuses: write
    secrets:
      NIXPKGS_CI_APP_PRIVATE_KEY: ${{ secrets.NIXPKGS_CI_APP_PRIVATE_KEY }}
    with:
      artifact-prefix: pr-
